# eureka service registry as eureka client
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         default-zone: http://localhost:8761/eureka
   instance: localhost 

# service specific properties
microservice:
   payment-service:
      endpoints:
         endpoint:
            uri: http://PAYMENT-SERVICE/payment
   order-service:
      endpoints:
         endpoint:
            uri: http://ORDER-SERVICE/order/bookOrder